name: "Wrap weth to eth"
on:
  schedule:
  - cron: "*/60 */${{ env.WRAP_TIME }} * * *"
  workflow_dispatch: {}

jobs:
  actions:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install web3==6.0.0
          pip install typing-extensions==4.9.0
      
      - name: Wrap weth to eth
        env:
            ADDRESS: ${{ secrets.ADDRESS }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
            POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
            BASE_RPC: ${{ secrets.BASE_RPC }}
            ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
        run: |
          python3 wrap_weth_to_eth.py
          echo "## Wraping weth" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
